# DO NOT DELETE

test_energy_mrt.o: ../metasim.hpp ../baseexc.hpp ../basestat.hpp
test_energy_mrt.o: ../basetype.hpp ../tick.hpp /usr/include/limits.h
test_energy_mrt.o: ../strtoken.hpp ../debugstream.hpp ../entity.hpp
test_energy_mrt.o: ../event.hpp ../simul.hpp ../particle.hpp ../plist.hpp
test_energy_mrt.o: ../trace.hpp ../factory.hpp ../genericvar.hpp
test_energy_mrt.o: ../randomvar.hpp ../cloneable.hpp ../gevent.hpp
test_energy_mrt.o: ../history.hpp ../regvar.hpp ../rttask.hpp ../task.hpp
test_energy_mrt.o: ../abstask.hpp ../kernel.hpp ../abskernel.hpp
test_energy_mrt.o: ../kernevt.hpp ../cpu.hpp ../timer.hpp ../powermodel.hpp
test_energy_mrt.o: ../taskevt.hpp ../feedback.hpp ../taskexc.hpp
test_energy_mrt.o: ../mrtkernel.hpp ../edfsched.hpp ../scheduler.hpp
test_energy_mrt.o: ../cbserver.hpp ../server.hpp ../resmanager.hpp
test_energy_mrt.o: ../capacitytimer.hpp
test_mrt.o: ../metasim.hpp ../baseexc.hpp ../basestat.hpp ../basetype.hpp
test_mrt.o: ../tick.hpp /usr/include/limits.h ../strtoken.hpp
test_mrt.o: ../debugstream.hpp ../entity.hpp ../event.hpp ../simul.hpp
test_mrt.o: ../particle.hpp ../plist.hpp ../trace.hpp ../factory.hpp
test_mrt.o: ../genericvar.hpp ../randomvar.hpp ../cloneable.hpp ../gevent.hpp
test_mrt.o: ../history.hpp ../regvar.hpp ../rttask.hpp ../task.hpp
test_mrt.o: ../abstask.hpp ../kernel.hpp ../abskernel.hpp ../kernevt.hpp
test_mrt.o: ../cpu.hpp ../timer.hpp ../powermodel.hpp ../taskevt.hpp
test_mrt.o: ../feedback.hpp ../taskexc.hpp ../mrtkernel.hpp ../edfsched.hpp
test_mrt.o: ../scheduler.hpp ../cbserver.hpp ../server.hpp ../resmanager.hpp
test_mrt.o: ../capacitytimer.hpp
