# Typical C++ working environment, see
# https://github.com/gabrieleara/working_environments/tree/master/cpp
FROM gabrieleara/dev_environment:cpp

# One of PARTSim may require boost-program-options dev library to build
# RUN export DEBIAN_FRONTEND=noninteractive && apt update  \
#     && apt -y install --no-install-recommends \
#     libboost-program-options-dev \
#     && apt -y autoremove \
#     && apt -y clean \
#     && rm -rf /var/lib/apt/lists/*
