#!/bin/bash

if [ "$1" = "h" ] ;then
	echo "Example: ./db energyMRTKernel.cpp 51"
else
	# this worked: gdbgui ./example --gdb-args=" -ex 'break energyMRTKernel.cpp:117' "
	LONGSTRINGS="set print elements 0"
	CATCHTHROWS="catch throw"
	gdbgui --gdb-args="-ex '$LONGSTRINGS' -ex '$CATCHTHROWS' -ex 'break "$1":"$2"' -ex 'r' ./example"
fi
